dcsaorg/DCSA-JIT

- datamodel/initdb.d/03_dcsa_ovs_v1_0.sql
- datamodel/testdata.d/05_test_data.sql
- pom.xml
- src/main/java/org/dcsa/ovs/controller/ScheduleController.java
- src/main/java/org/dcsa/ovs/controller/ScheduleSubscriptionController.java
- src/main/java/org/dcsa/ovs/controller/ScheduleTransportCallController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallSubscriptionController.java
- src/main/java/org/dcsa/ovs/model/Schedule.java
- src/main/java/org/dcsa/ovs/model/TransportCall.java
- src/main/java/org/dcsa/ovs/service/impl/ScheduleServiceImpl.java
- src/main/java/org/dcsa/ovs/service/impl/TransportCallServiceImpl.java
change vesselIMONumber fro Integer -> String
Change date_range input data to validate against: ^(P(\dY)?(\dM)?(\dD)?)?(T(\dH)?(\dM)?(\dS)?)?$
Bump Spring Boot to 2.3.5
Bump Core to 0.7.0
Changed POST calls to controllers to call create instead of save on service-class
> Multiple changes

- datamodel/initdb.d/03_dcsa_ovs_v1_0.sql
- datamodel/testdata.d/05_test_data.sql
- src/main/java/org/dcsa/ovs/model/TransportCall.java
Change Vessel IMO Number from number type to String type
Vessel IMO Number *must* be 7 decimals
> Change vesselIMO Number to string (7 characters)

- datamodel/initdb.d/03_dcsa_ovs_v1_0.sql
- datamodel/testdata.d/05_test_data.sql
- pom.xml
- src/main/java/org/dcsa/ovs/model/ScheduleSubscription.java
- src/main/java/org/dcsa/ovs/model/TransportCall.java
- src/main/java/org/dcsa/ovs/model/TransportCallSubscription.java
Change vesselIMONumber to string type
Fix invalid vesselIMONumber
Bump Core version
Use Core validations
> Add validation to vesselIMONumber

- pom.xml
- src/main/java/org/dcsa/ovs/model/Event.java
- src/main/java/org/dcsa/ovs/model/TransportEvent.java
- src/main/java/org/dcsa/ovs/service/impl/ScheduleServiceImpl.java
- src/main/java/org/dcsa/ovs/service/impl/ScheduleSubscriptionServiceImpl.java
- src/main/java/org/dcsa/ovs/service/impl/TransportCallServiceImpl.java
- src/main/java/org/dcsa/ovs/service/impl/TransportCallSubscriptionServiceImpl.java
- src/main/java/org/dcsa/ovs/service/impl/TransportEventServiceImpl.java
Enables us to drop a bit of dead-weight boilerplate code.
> Bump DCSA-Core to 0.7.12

- pom.xml
- src/main/java/org/dcsa/ovs/controller/ScheduleTransportCallController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallOperationsEventController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallTransportEventController.java
- src/main/java/org/dcsa/ovs/model/TransportCall.java
- src/main/java/org/dcsa/ovs/model/Vessel.java
- src/main/java/org/dcsa/ovs/repository/VesselRepository.java
- src/main/java/org/dcsa/ovs/service/TransportCallService.java
- src/main/java/org/dcsa/ovs/service/VesselService.java
- src/main/java/org/dcsa/ovs/service/impl/TransportCallServiceImpl.java
- src/main/java/org/dcsa/ovs/service/impl/VesselServiceImpl.java
merging back the nested vessel
> Fixed nested Vessel!

- pom.xml
- src/main/java/org/dcsa/ovs/Application.java
- src/main/java/org/dcsa/ovs/controller/ScheduleController.java
- src/main/java/org/dcsa/ovs/controller/ScheduleSubscriptionController.java
- src/main/java/org/dcsa/ovs/controller/ScheduleTransportCallController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallPortCallEventController.java
- src/main/java/org/dcsa/ovs/controller/TransportCallSubscriptionController.java
- src/main/java/org/dcsa/ovs/controller/TransportEventController.java
> Removed swagger annotations and dependency

- pom.xml
Part of issue : dcsaorg/DCSA-Core#79
> Renamed dcsa.tag to dcsa.core.tag

- ovs/v2/ovs.yaml
> Push from SwaggerHub.

- pom.xml
- src/main/java/org/dcsa/ovs/controller/TimestampController.java
- src/main/java/org/dcsa/ovs/model/Timestamp.java
- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
Related: https://github.com/dcsaorg/DCSA-Event-Core/pull/36
Issue: https://dcsa.atlassian.net/browse/DDT-208
> DDT:208 Add missing fields in OperationsEvent

- src/main/java/org/dcsa/ovs/model/Timestamp.java
Use FacilityTypeCode Enum in OVS TimeStamp
> Ddt 213 add facility type code enum

- src/main/java/org/dcsa/ovs/model/Timestamp.java
- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
> DDT-256: Add delay reason code + remark to Timestamp

- .github/workflows/microservices.yml
- pom.xml
- src/main/java/org/dcsa/ovs/model/Timestamp.java
- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
- src/main/resources/application.yaml
> Bump Dependencies to use `@ValidVesselIMONumber`

- .github/workflows/microservices.yml
> CI: Reset API validator branch to master

- .github/workflows/microservices.yml
> CI: Use API Validator master again

- .github/workflows/microservices.yml
- pom.xml
- src/main/java/org/dcsa/ovs/model/Timestamp.java
- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
Still need to find a way to create a valid vessel, if it does not exists. Currently, it creates a vessel with a hardcoded carrier and the given IMO number.
~~Depends on https://github.com/dcsaorg/DCSA-Event-Core/pull/74~~
> DDT-292 create transport call if missing

- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
> On creating a TC via timestamp, set facilityTypeCode to POTE

- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
The `vesselIMONumber` is always present, so the `NOT_IMPLEMENTED` case
does not occur in practise.
> Remove NOT_IMPLEMENTED case

- Dockerfile
- run-in-container.sh
> Docker: Support external config

- src/main/java/org/dcsa/ovs/service/impl/TimestampServiceImpl.java
> DDT-340: Remove 501 Not implemented guard

- pom.xml
> Bump DCSA-(Event-)Core

- .github/workflows/docker_publish.yml
- .github/workflows/microservices.yml
- Dockerfile
- README.md
- docker-compose.yml
- pom.xml
- src/main/java/org/dcsa/jit/Application.java
- src/main/java/org/dcsa/jit/config/ApplicationConfig.java
- src/main/java/org/dcsa/jit/controller/EventController.java
- src/main/java/org/dcsa/jit/controller/JITEventSubscriptionTOController.java
- src/main/java/org/dcsa/jit/controller/TimestampController.java
- src/main/java/org/dcsa/jit/controller/TransportCallSubscriptionController.java
- src/main/java/org/dcsa/jit/model/Timestamp.java
- src/main/java/org/dcsa/jit/model/TransportCallSubscription.java
- src/main/java/org/dcsa/jit/model/enums/TransportDocumentType.java
- src/main/java/org/dcsa/jit/model/enums/TransportEventCode.java
- src/main/java/org/dcsa/jit/model/transferobjects/JITEventSubscriptionTO.java
- src/main/java/org/dcsa/jit/model/transferobjects/VesselPositionTO.java
- src/main/java/org/dcsa/jit/repository/TransportCallSubscriptionRepository.java
- src/main/java/org/dcsa/jit/service/JITEventService.java
- src/main/java/org/dcsa/jit/service/TimestampService.java
- src/main/java/org/dcsa/jit/service/TransportCallSubscriptionService.java
- src/main/java/org/dcsa/jit/service/impl/JITEventServiceImpl.java
- src/main/java/org/dcsa/jit/service/impl/JITEventSubscriptionTOServiceImpl.java
- src/main/java/org/dcsa/jit/service/impl/TimestampServiceImpl.java
- src/main/java/org/dcsa/jit/service/impl/TransportCallSubscriptionServiceImpl.java
- src/main/java/org/dcsa/ovs/service/OVSEventService.java
- src/main/resources/application.yaml
> DDT-466: Rename OVS to JIT

- .github/workflows/microservices.yml
> CI: Reset branch

- pom.xml
- src/main/java/org/dcsa/jit/model/Timestamp.java
- src/main/java/org/dcsa/jit/service/impl/TimestampServiceImpl.java
- This was prompted by issue DDT-519
- Ensure phasetyp in OVS-notifications.
- Related to [OVS-Core-DDT-519] (https://github.com/dcsaorg/DCSA-Event-Core/pull/122)
- Related to [OVS-Notifications-DDT-519] (https://github.com/dcsaorg/DCSA-OVS-Notifications/pull/24)
> DDT-519 bump and align to newest EventCore

- pom.xml
- src/main/java/org/dcsa/jit/service/impl/TimestampServiceImpl.java
> Bump DCSA-Event-Core to fix DDT-560

- .github/workflows/docker_publish.yml
> CI: Build images for all live-* branches

- .github/workflows/microservices.yml
- src/main/java/org/dcsa/jit/controller/TimestampController.java
- src/main/java/org/dcsa/jit/model/OpsEventTimestampDefinition.java
- src/main/java/org/dcsa/jit/model/Payload.java
- src/main/java/org/dcsa/jit/repository/OpsEventTimestampDefinitionRepository.java
- src/main/java/org/dcsa/jit/repository/PayloadRepository.java
- src/main/java/org/dcsa/jit/service/TimestampService.java
- src/main/java/org/dcsa/jit/service/impl/TimestampServiceImpl.java
> DDT-690: Record json payloads on POST timestamps

- src/main/java/org/dcsa/jit/util/ExtendedOperationsEventRequest.java
> DDT-756: Add UNLocationCode as query parameter for /events

- .github/workflows/docker_publish.yml
> Fix docker build

- src/main/java/org/dcsa/jit/service/impl/TimestampServiceImpl.java
Depends on https://github.com/dcsaorg/DCSA-Event-Core/pull/345
> DDT-1048: Terminal Call based Transport Calls

- src/test/java/jit/v1/PostTimestampsIT.java
add test case for timestamp - field publisher with only IdentifyingCodes
> DDT-1013: add test for timestamp Idcodes

- jit-persistence/pom.xml
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Party.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Service.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TransportCall.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Vessel.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Voyage.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/OperationsEventRepository.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/TransportCallRepository.java
- jit-service/pom.xml
- jit-service/src/main/java/org/dcsa/jit/Application.java
- pom.xml
Not done yet, but Abdi and Martin needs the references to shared-kernel and some initial Jpa setup
> DDT-1084 - part1

- .github/workflows/docker_publish.yml
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Party.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Service.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TimestampDefinition.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TransportCall.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/Vessel.java
- jit-service/src/main/resources/application.yml
> Align some JIT entities with the database

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OpsEventTimestampDefinition.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/OpsEventTimestampDefinitionRepository.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampDefinitionService.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/OperationsEventTO.java
> Minor corretions to assist UI-Support

- jit-service/src/main/java/org/dcsa/jit/service/TimestampService.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/TimestampTO.java
- Build timestamp for if clauses
- Avoid nullPointerException
> minor fixes based on IT feedback 

- jit-integration-tests/pom.xml
- jit-integration-tests/src/main/java/org/dcsa/jit/itests/config/RestAssuredConfigurator.java
- jit-integration-tests/src/main/java/org/dcsa/jit/itests/config/TestUtil.java
- jit-integration-tests/src/main/java/org/dcsa/jit/itests/v1/PostTimestampsIT.java
- jit-integration-tests/src/main/resources/InvalidEventTypeEventSubscriptionSample.json
- jit-integration-tests/src/main/resources/InvalidVesselIMONumberEventSubscriptionSample.json
- jit-integration-tests/src/main/resources/TimestampSample.json
- jit-integration-tests/src/main/resources/ValidEventSubscriptionSample.json
- jit-integration-tests/src/main/resources/schema/error.json
- jit-integration-tests/src/main/resources/schema/operationsEvent.json
> DDT-1088: Integration tests

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TimestampDefinition.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TransportCall.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/enums/FacilityTypeCodeOPR.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/enums/FacilityTypeCodeTRN.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/TimestampDefinitionRepository.java
- jit-service/src/main/java/org/dcsa/jit/mapping/EnumMappers.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampService.java
- jit-service/src/main/java/org/dcsa/jit/service/TransportCallService.java
- jit-service/src/test/java/org/dcsa/jit/service/TimestampDefinitionServiceTest.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/OperationsEventTO.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/TimestampTO.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/TransportCallTO.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/enums/FacilityTypeCodeOPR.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/enums/FacilityTypeCodeTRN.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/enums/PortCallServiceTypeCode.java
- define FacilityTypecode with respect to types given in JIT v1.2 specification
- temporarily default created TR's to FacilityTypecode  -> POTE
> def FacilityTypecode in accordance with JITv1.2

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
- jit-service/src/main/java/org/dcsa/jit/mapping/TransportCallMapper.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampService.java
> Fix mapping and validation bugs

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/enums/FacilityTypeCodeOPR.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/enums/FacilityTypeCodeOPR.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-1116
> Added ANCH Facility Type

- jit-integration-tests/src/main/resources/schema/operationsEvent.json
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/enums/PortCallServiceTypeCode.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/enums/PortCallServiceTypeCode.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-1117
> Added new portcall service types

- jit-integration-tests/src/main/java/org/dcsa/jit/itests/v1/PostTimestampsIT.java
- jit-service/src/main/java/org/dcsa/jit/service/TransportCallService.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/TimestampTO.java
- removed unnecessary null checks in code
- added test case for XOR logic
- added carrierVoyageNumber field
> DDT-1005: /related bugs - refactor & add XOR logic for voyage numbers

- jit-integration-tests/src/main/java/org/dcsa/jit/itests/v1/OperationsEventIT.java
- jit-integration-tests/src/main/resources/TimestampSample.json
Resolves:
https://dcsa.atlassian.net/browse/DDT-1052
> Updated sample data for timestamp in IT

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/PublisherPattern.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TimestampDefinition.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/TimestampDefinitionRepository.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampDefinitionService.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampService.java
- jit-service/src/test/java/org/dcsa/jit/service/TimestampDefinitionServiceTest.java
This PR aligns JIT with the latest timestamp definition format defined in the IM.
> DDT-1140: JIT 1.2 timestamp definition

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/enums/DimensionUnit.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/OperationsEventTO.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-1135
> Added vesselDraftUnit to operations event.

- jit-service/src/main/java/org/dcsa/jit/mapping/VesselMapper.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/VesselTO.java
- check vesselOperatorCarrier for null
- remove wrong constraint on dimensionUnit
- add explicit mappings on VesselTO mapping
> handle null exception & remove wrong constraint

- jit-application/pom.xml
- jit-application/src/main/java/org/dcsa/jit/security/AudienceValidator.java
- jit-application/src/main/java/org/dcsa/jit/security/ClaimShape.java
- jit-application/src/main/java/org/dcsa/jit/security/ClaimsOneOfValueValidator.java
- jit-application/src/main/java/org/dcsa/jit/security/JwtAuthenticationConverter.java
- jit-application/src/main/java/org/dcsa/jit/security/SecurityConfig.java
- jit-application/src/main/java/org/dcsa/jit/security/SecurityConfigProd.java
- jit-application/src/test/java/org/dcsa/jit/controller/OperationsEventControllerTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-1139
> Migrated security configs

- jit-application/src/test/java/datafactories/OperationsEventTODataFactory.java
- jit-application/src/test/java/org/dcsa/jit/controller/OperationsEventControllerTest.java
- jit-service/src/test/java/org/dcsa/jit/service/TimestampDefinitionServiceTest.java
- jit-service/src/test/java/org/dcsa/jit/service/datafactories/TimestampDefinitionDataFactory.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-1195
> Added datafactories

- jit-service/src/main/java/org/dcsa/jit/mapping/VesselMapper.java
> Make the vesselMapper do two way mappings

- jit-application/src/main/java/org/dcsa/jit/controller/TimestampController.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/IdentifyingCodeTO.java
> DDT-1200: Add missing codeListResponisbleAgencyCode

- jit-integration-tests/src/main/java/org/dcsa/jit/itests/v1/PostTimestampsIT.java
- jit-integration-tests/src/main/resources/TimestampSample_v1-1.json
- jit-service/src/main/java/org/dcsa/jit/service/TimestampService.java
> DDT-1203 [3/4]: Reject vesselPosition on TS that do not allow them

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/TimestampDefinition.java
> Add implicitVariantOf to TimestampDefinition

- jit-application/src/main/java/org/dcsa/jit/controller/TimestampController.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/UISupportVesselTO.java
- UI does not use this field in UISupportVesselTO
> remove redundant vesselDraft

- jit-application/pom.xml
- jit-application/src/test/java/org/dcsa/jit/security/SecurityFlowIT.java
- jit-application/src/test/resources/keycloak/realm-export.json
- pom.xml
> Added a testcontainer to test prod security configs.

- doc/Module 9 part 1 - preparing an ETA-Berth.md
- doc/Module 9 part 2 - receiving an RTA-Berth.md
- doc/Module 9 part 3 - classifying timestamps.md
> DDT-1219: Create module 9 of the adoption pack

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/MessageRoutingRule.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/MessageRoutingRuleRepository.java
- jit-persistence/src/main/java/org/dcsa/jit/persistence/repository/specification/MessageRoutingRuleSpecification.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampRoutingService.java
- jit-service/src/test/java/org/dcsa/jit/service/TimestampRoutingServiceTest.java
> DDT-1224: Add publisherRole to MessageRoutingRule

- jit-notifications/src/main/java/org/dcsa/jit/notifications/model/MailTemplate.java
- jit-notifications/src/test/java/org/dcsa/jit/notifications/model/MailTemplateTest.java
> DDT-1248: Support onlyWhenOperationsEventTypeCode

- .github/workflows/docker_publish.yml
- .github/workflows/publishRelease.yml
- pom.xml
> Post release bump

- jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
- jit-service/src/main/java/org/dcsa/jit/service/TimestampService.java
- jit-service/src/test/java/org/dcsa/jit/service/mapping/OperationsEventMapperTest.java
- jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/TimestampTO.java
- postman_collection.json
- Added test for duplicate timestampID
> DDT-1337: Added timestampID to TimestampTO

- jit-application/src/main/resources/application.yml
- pom.xml
- postman_collection.combinatorial.json
- postman_collection.json
(and remove a redundant dependency declaration)
Closes: #199
> DDT-1438: Correct specification version
